executable("azecotron_host") {
  sources = [
    "azecotron_app_main.cc",
    "synth_browser_context.cc",
    "synth_browser_context.h",
    "synth_browser_main_parts.cc",
    "synth_browser_main_parts.h",
    "synth_content_browser_client.cc",
    "synth_content_browser_client.h",
    "synth_content_main_delegate.cc",
    "synth_content_main_delegate.h",
    "synth_tracker_rules.cc",
    "synth_tracker_rules.h",
    "synth_tracker_throttle.cc",
    "synth_tracker_throttle.h",
    "synth_devtools_delegate.cc",
    "synth_devtools_delegate.h",
    "synth_devtools_manager_delegate.cc",
    "synth_devtools_manager_delegate.h",
    "synth_permission_controller_delegate.cc",
    "synth_permission_controller_delegate.h",
    "synth_download_manager_delegate.cc",
    "synth_download_manager_delegate.h",
  ]

  deps = [
    "//azecotron/host:azecotron_runtime_host",
    "//base",
    "//build:branding_buildflags",
    "//components/download/public/common",
    "//content",
    "//content/public/app",
    "//content/public/browser",
    "//content/public/common",
    "//services/network/public/cpp",
    "//third_party/blink/public/common",
    "//url",
    "//sandbox",
  ]

  data = [
    "synth_tracker_rules.json",
  ]

  if (is_win) {
    configs -= [ "//build/config/win:default_incremental_linking" ]
    configs += [ "//build/config/win:default_large_module_incremental_linking" ]
  }
}

group("azecotron") {
  deps = [
    ":azecotron_host",
  ]
}
