executable("azecotron_host") {
  sources = [
    "azecotron_app_main.cc",
    "synth_browser_context.cc",
    "synth_browser_context.h",
    "synth_browser_main_parts.cc",
    "synth_browser_main_parts.h",
    "synth_content_browser_client.cc",
    "synth_content_browser_client.h",
    "synth_content_main_delegate.cc",
    "synth_content_main_delegate.h",
    "synth_tracker_throttle.cc",
    "synth_tracker_throttle.h",
    "synth_permission_controller_delegate.cc",
    "synth_permission_controller_delegate.h",
    "synth_download_manager_delegate.cc",
    "synth_download_manager_delegate.h",
  ]

  deps = [
    "//build/win:default_exe_manifest",
    "//azecotron/host:azecotron_runtime_host",
    "//content",
    "//content/public/app",
    "//content/public/browser",
    "//content/public/common",
    "//services/network/public/cpp",
    "//third_party/blink/public/common",
    "//sandbox",
  ]

  data_deps = [
    "//tools/v8_context_snapshot:v8_context_snapshot",
  ]

  if (is_win) {
    configs -= [ "//build/config/win:default_incremental_linking" ]
    configs += [ "//build/config/win:default_large_module_incremental_linking" ]
  }
}

group("azecotron") {
  deps = [
    ":azecotron_host",
  ]
}
